### ISSUE TITLE
Can we have an example of how to use Matrix?

### ISSUE THREAD

**Issue by andyyankai** [lubkoll/funcy#1]
In the example, there are many times using class matrix.
However, there isn't anything discuss where is this class come from and how to define the matrix.

**Comment by lubkoll** [comment]
Are you familiar with the concepts of matrices and vectors? funcy has generic support for matrices (and to lesser extent for vectors). Thus you may use any popular linear-algebra library (i.e. I suggest Eigen).

In the subfolder test/linear_algebra you will find a file determinant.cpp. There matrices from the Eigen-library are used, so you may use this as an example.


I hope this helps.

**Comment by lubkoll** [comment]
For getting Eigen in ubuntu use:
apt install libeigen3-dev
