### ISSUE TITLE
Is funcy thread safe?

### ISSUE THREAD

**Issue by andyyankai** [lubkoll/funcy#2]
I ran a test comparing a single-thread and multi-thread execution (OpenMP), the results didn't match.

**Comment by lubkoll** [comment]
No, funcy is not thread-safe. It is designed for highest achievable performance, thus any locking or even atomic operation is of disadvantage.
Moreover I don't expect that you will get any performance improvements in a multi-threaded environment. Or do you just want to share the function and evaluate it in different threads? As long as you call the member function 'update' only from one thread, then (after you made sure that 'update' terminated) evaluation of the function and derivatives should be safe (as caching only happens in the 'update'-call).  
Does this help? Else I can provide a thread-safe wrapper if that is what you need.

**Comment by andyyankai** [comment]
Thanks, that makes it clear. I might not need thread-safe so far.
