### ISSUE TITLE
How to calculate a series using FunG?

### ISSUE THREAD

**Issue by andyyankai** [lubkoll/funcy#4]
I am trying to test the following algorithm using FunG something like
# begin code
auto u = FunG::Pow<3>(1.) + FunG::Sin(1.)(FunG::Sqrt(1.));
u = u +  u^2; #something like this
auto f_fung_opt = FunG::finalize(u);
  for(auto i=0; i<iter; ++i)
  {
    f_fung_opt.update(x);
    f = f_fung_opt();
    dfdx = f_fung_opt.d1(1.);
    x *= scaling;
  }
# end code
Is there anyway to do test like this in funG? It looks like FunG cannot support "=" and some operator in my experience.

**Comment by lubkoll** [comment]
The problem with '=' in the above example is that 'u' and 'u + u ^2' have different types (as all the information on mathematical operations and derivative rules are expressed there, you may look up 'expression templates' to get an idea of the technique). So you need to introduce a new variable for the latter. More generic approaches (i.e. using type-erasure) can we wrapped around FunG, but that significantly slows down computations as it blocks inlining and is often not necessary. 
Besides that FunG supports all mathematically required operations and some more. All these are thoroughly tested and used by researchers in their models for some years now, so I am sure that they work. What is not provided, for a very good reason, is the division operator '/'. This is important as division is just a short cut multiplication with inverse elements for scalars, but does not exist for vectors, matrices, linear operators or other types. You may look into the paper, there is a concrete list of requirements on types and how they model functions that operate on linear spaces.

Also be aware that using '^2' is dangerous. I don't do it any more and plan to remove this soon. It is convenient to be able to write 'x^2', but the in C++ the operator precedence rules for '^' are not consistent with the mathematical interpretation. This can lead to really unexpected results if you don't add parenthesis, i.e. '(u^2)' or better use the replacement 'squared(u)'.

**Comment by andyyankai** [comment]
Actually in my example, I want to use a loop to generate a long series and find the derivative.
for example
auto u = FunG::Pow<3>(1.) + FunG::Sin(1.)(FunG::Sqrt(1.));
for (i=0; i<100; ++i) {
    "a new u" = u + squared(u);
}
Do you know how can to introduce a new variable each time in the loop and use the value from the pervious loop?

**Comment by lubkoll** [comment]
You can do that by using template programming. I.e. this should do the job:

template<int N>
struct ComputeSeries
{
    template <class Function>
    static auto apply(const Function& u)
    {
        const auto v = u + squared(u);
        return ComputeSeries<N-1>::apply(v);
    }
};

template <>
struct ComputeSeries<0>
{
    template <class Function>
    static Function apply(const Function& u)
    {
        return u;
    }
};

Then 'ComputeSeries<N>::apply(u)' provides the sequence you are looking for.
